export interface ServiceCategory {
  title: string;
  description: string;
  img: string;
  alt: string;
  subCategories: string[];
  popular?: boolean;
}

export const services: ServiceCategory[] = [
  {
    title: 'Vehicle Repairs & Services',
    description: 'Car, motorbike, and three-wheeler repairs, tyres, batteries, and vehicle electrical work.',
    img: '/services/vehicle-repairs.jpg',
    alt: 'Mechanic repairing a vehicle',
    subCategories: [
      'Car / van repairs',
      'Motorbike repairs',
      'Three-wheeler (tuk-tuk) repairs',
      'Tyre fitting & puncture repair',
      'Battery replacement',
      'AC service & repair',
      'Windscreen & glass repair',
      'Vehicle electrical work',
      'Oil change & lubrication',
      'Vehicle body & panel work',
      'Painting & polishing',
      'Other – please specify',
    ],
  },
  {
    title: 'Plumbing',
    description: 'Leak detection, pipe repairs, water tanks, and fixture installations.',
    img: '/services/plumbing.jpg',
    alt: 'Plumber fixing a sink',
    subCategories: [
      'Pipe installation & repairs',
      'Tap & valve replacement',
      'Water tank installation',
      'Toilet & cistern repairs',
      'Drainage & sewage clearing',
      'Water pump installation',
      'Hot water system / solar heater',
      'Overhead tank cleaning',
      'Leak detection & fixing',
      'Bathroom fitting',
      'Other – please specify',
    ],
  },
  {
    title: 'Masonry & Construction',
    description: 'Construction, plastering, tiling, roof slabs, and renovation work.',
    img: '/services/masonry-construction.jpg',
    alt: 'Construction and masonry work',
    subCategories: [
      'New house construction',
      'Wall plastering',
      'Brick & block laying',
      'Tile fixing (floor & wall)',
      'Concrete work & roof slabs',
      'Compound wall / fencing',
      'Waterproofing & damp proofing',
      'Demolition work',
      'Well construction & repair',
      'Renovation & extension work',
      'Other – please specify',
    ],
  },
  {
    title: 'Carpentry & Woodwork',
    description: 'Custom furniture, cabinets, wardrobes, flooring, and wood repair.',
    img: '/services/carpentry-woodwork.jpg',
    alt: 'Carpenter working on wood furniture',
    subCategories: [
      'Door & window frames',
      'Custom furniture making',
      'Roof timber work',
      'Cabinet & wardrobe fitting',
      'Flooring (wood / laminate)',
      'Partition walls',
      'Staircase construction',
      'Wooden repair & polishing',
      'Kitchen fitting',
      'Other – please specify',
    ],
  },
  {
    title: 'Electrical Work',
    description: 'House wiring, switchboards, lighting, solar, and fault finding.',
    popular: true,
    img: '/services/electrical-work.jpg',
    alt: 'Electrician working on wiring',
    subCategories: [
      'House wiring',
      'Switchboard & DB installation',
      'Lighting installation',
      'Fan & AC wiring',
      'Solar panel installation',
      'Generator / inverter setup',
      'CCTV & security systems',
      'Home theatre & TV mounting',
      'Electrical fault finding',
      'Other – please specify',
    ],
  },
  {
    title: 'Painting & Finishing',
    description: 'Interior/exterior painting, waterproofing coatings, and decorative finishes.',
    img: '/services/painting-finishing.jpg',
    alt: 'Painter finishing a wall',
    subCategories: [
      'Interior wall painting',
      'Exterior painting',
      'Wood & metal painting',
      'Waterproofing coatings',
      'Texture & decorative finishes',
      'Anti-rust treatment',
      'Roof painting',
      'Whitewashing',
      'Other – please specify',
    ],
  },
  {
    title: 'AC & Appliance Repair',
    description: 'AC installation & gas refilling, washing machines, fridges, and more.',
    img: '/services/ac-appliance-repair.jpg',
    alt: 'Air conditioner being repaired',
    subCategories: [
      'AC installation & service',
      'AC gas refilling',
      'Washing machine repair',
      'Refrigerator repair',
      'Microwave & oven repair',
      'Television repair',
      'Sewing machine repair',
      'Water purifier service',
      'Gas cooker repair',
      'Other – please specify',
    ],
  },
  {
    title: 'Gardening & Landscaping',
    description: 'Garden maintenance, lawn mowing, tree cutting, and landscaping design.',
    img: '/services/gardening-landscaping.jpg',
    alt: 'Gardener landscaping a yard',
    subCategories: [
      'Garden maintenance',
      'Lawn mowing & trimming',
      'Tree cutting & pruning',
      'Pest control (garden)',
      'Garden design & planting',
      'Irrigation system setup',
      'Outdoor paving',
      'Other – please specify',
    ],
  },
  {
    title: 'Cleaning Services',
    description: 'Home deep cleaning, office cleaning, carpet & sofa cleaning, and pest control.',
    img: '/services/cleaning-services.jpg',
    alt: 'Home cleaning professional',
    subCategories: [
      'Home deep cleaning',
      'Office / commercial cleaning',
      'Post-construction cleaning',
      'Carpet & sofa cleaning',
      'Water tank & sump cleaning',
      'Pest control (home)',
      'Septic tank cleaning',
      'Window cleaning',
      'Other – please specify',
    ],
  },
  {
    title: 'Security & Safety',
    description: 'CCTV, electric fences, alarm systems, and smart lock installation.',
    img: '/services/security-safety.jpg',
    alt: 'CCTV security camera installation',
    subCategories: [
      'CCTV installation',
      'Electric fence installation',
      'Alarm system setup',
      'Fire extinguisher service',
      'Smart lock installation',
      'Security guard services',
      'Other – please specify',
    ],
  },
  {
    title: 'IT & Electronics',
    description: 'Computer & laptop repair, networking, phone screens, and smart home setup.',
    img: '/services/it-electronics.jpg',
    alt: 'Technician repairing electronics',
    subCategories: [
      'Computer / laptop repair',
      'Networking & WiFi setup',
      'Phone screen replacement',
      'Data recovery',
      'Software installation',
      'Printer repair & service',
      'Smart home setup',
      'Other – please specify',
    ],
  },
  {
    title: 'Moving & Transport',
    description: 'House and office moving, furniture delivery, and lorry/van hire.',
    img: '/services/moving-transport.jpg',
    alt: 'Movers loading a delivery van',
    subCategories: [
      'House moving services',
      'Office relocation',
      'Furniture delivery',
      'Lorry / van hire',
      'Packing & unpacking',
      'Waste & junk removal',
      'Other – please specify',
    ],
  },
];
